import re
import logging
from typing import List, Dict, Any, Tuple
from app.schemas.evidence import Citation

logger = logging.getLogger(__name__)

class CitationValidator:
    """
    Validates and standardizes citation references in the generated answer.
    It prevents page number hallucinations by mapping inline citation tags
    (e.g., [1] or [chunk-id]) strictly to verified Qdrant point metadata.
    """

    def validate_and_build_citations(
        self,
        draft_answer: str,
        evidence_chunks: List[Dict[str, Any]]
    ) -> Tuple[str, List[Citation]]:
        """
        Scans draft_answer for mentions of evidence, standardizes citation numbers [1], [2], etc.,
        and returns a cleaned answer with a list of Pydantic Citation objects.
        """
        if not draft_answer or not evidence_chunks:
            return draft_answer, []

        citations: List[Citation] = []
        chunk_map = {}
        
        # Build map of chunk_id to chunk index and metadata
        for i, chunk in enumerate(evidence_chunks):
            chunk_id = str(chunk.get("chunk_id", ""))
            chunk_map[chunk_id] = {
                "index": i + 1,
                "data": chunk
            }

        # 1. Look for explicit chunk-id patterns generated by LLM (e.g. [chunk-xxx])
        # and map them to clean numeric markers [1], [2] based on their Qdrant results index.
        cleaned_text = draft_answer
        found_chunk_ids = re.findall(r'\[chunk-([^\]]+)\]', cleaned_text)
        
        for c_id in found_chunk_ids:
            full_c_id = f"chunk-{c_id}"
            if full_c_id in chunk_map:
                marker_idx = chunk_map[full_c_id]["index"]
                cleaned_text = cleaned_text.replace(f"[{full_c_id}]", f"[{marker_idx}]")
                
                # Add to citations if not already added
                self._add_citation_if_missing(citations, chunk_map[full_c_id]["data"])

        # 2. Look for general numeric markers like [1], [2] in LLM output and verify their validity.
        found_numeric_markers = re.findall(r'\[(\d+)\]', cleaned_text)
        for num_str in found_numeric_markers:
            idx = int(num_str) - 1
            if 0 <= idx < len(evidence_chunks):
                self._add_citation_if_missing(citations, evidence_chunks[idx])
            else:
                # Remove invalid/hallucinated numeric markers
                cleaned_text = cleaned_text.replace(f"[{num_str}]", "")

        # 3. Heuristic matching: If no explicit markers are found, scan the text
        # to map sentences to the most relevant evidence chunk.
        if not citations:
            sentences = re.split(r'(?<=[.!?])\s+', cleaned_text.strip())
            updated_sentences = []
            
            for sentence in sentences:
                sentence_lower = sentence.lower()
                best_match_chunk = None
                max_keyword_matches = 0
                
                for chunk in evidence_chunks:
                    chunk_text = chunk.get("text", chunk.get("chunk_text", "")).lower()
                    # Count matching words of significant length (exclude common short stopwords)
                    stopwords = {"the", "and", "for", "with", "that", "this", "from", "are", "not", "but", "have"}
                    chunk_words = set([w for w in re.findall(r'\b\w+\b', chunk_text) if len(w) >= 3 and w not in stopwords])
                    matches = sum(1 for w in chunk_words if w in sentence_lower)
                    
                    if matches > max_keyword_matches and matches >= 3:
                        max_keyword_matches = matches
                        best_match_chunk = chunk
                
                if best_match_chunk:
                    self._add_citation_if_missing(citations, best_match_chunk)
                    # Find index of this chunk in the final citations list
                    cit_idx = self._find_citation_index(citations, best_match_chunk.get("chunk_id"))
                    updated_sentences.append(f"{sentence} [{cit_idx}]")
                else:
                    updated_sentences.append(sentence)
                    
            cleaned_text = " ".join(updated_sentences)

        # Remove duplicate spaces or punctuation issues after substitutions
        cleaned_text = re.sub(r'\s+', ' ', cleaned_text).strip()

        return cleaned_text, citations

    def _add_citation_if_missing(self, citations: List[Citation], chunk: Dict[str, Any]):
        """Helper to append a unique Citation object to list."""
        chunk_id = str(chunk.get("chunk_id", ""))
        if any(c.chunk_id == chunk_id for c in citations):
            return
            
        citations.append(
            Citation(
                document_id=str(chunk.get("document_id", "")),
                document_name=str(chunk.get("document_name", "Unknown Document")),
                page=int(chunk.get("page_no", 1)),
                section=chunk.get("section"),
                chunk_id=chunk_id
            )
        )

    def _find_citation_index(self, citations: List[Citation], chunk_id: Any) -> int:
        """Finds 1-based index of a chunk in the citations list."""
        for idx, cit in enumerate(citations):
            if cit.chunk_id == str(chunk_id):
                return idx + 1
        return 1

# Singleton instance
citation_validator = CitationValidator()
